Publish 2020-03-Aproductsuverystory
MyGet/blog.myget.org pull request #32
Opened 2020-03-31 18:52 UTC by m00nlitcat

2020-04-02 14:13 UTC, m00nlitcat commented
@matthcap & @kacper-r here's the blog post for review, hoping everything works :)

2020-04-02 15:04 UTC, matthcap requested changes
great draft, looks like there are a few minor edits to make and we need to update the image paths to `/images/2020/filename.jpg` instead of `images/filename.jpg`, then we should be good to have Kacper review!

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +--->
we can delete this

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +title: "A Product Survey Story: What we learned"
all caps for the title

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +# A Product Survey Story: What we learned 🧐
I think we want all caps for post header

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +![Who uses my get?](images/Who-uses-MyGet?.jpg )
I think this should be `/images/2020/who-uses-MyGet?.jpg`

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +**In its early days, MyGet was lovingly introduced as  “NuGet-as-a-service”. That was the need it was built to solve—an easy way for you to get the benefits of a private NuGet server without the head
the header line should. be
```
## .NET, JavaScript, HTML: The Top 3
```

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +Over 98% of you responded that you are currently using source control for the proprietary code you write, which is a good thing: source control is a must-have for modern software development. Almost
delete `\` at the end of this line

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +![alt_text](images/What-do-you-use-CI-CD.jpg)
replace `alt_text`

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +![alt_text](images/What-is-your-primary-use.jpg)
`alt_text`

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> + \
delete `\`

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +MyGet’s success depends on our ability to continually improve features and build new ones that make your lives easier and help you ship better products. Despite the rise and adoption of 3rd-party CI/
grammar edit I just caught:
`MyGet's success depends on our ability to continually improve and build new features that make your...`

2020-04-02 15:04 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +Please reach out! We love hearing your stories and suggestions. You can reach us at [support@myget.org,](mailto:support@myget.org) start a chat with us at [https://myget.org,](https://myget.org) or c
delete `****` after UserVoice link

2020-04-02 16:38 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +----
this should be just three `---`, I believe @m00nlitcat

2020-04-02 16:38 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +**In its early days, MyGet was lovingly introduced as  “NuGet-as-a-service”. That was the need it was built to solve—an easy way for you to get the benefits of a private NuGet server without the head
still missing a `,` between JavaScript and HTML I think!

2020-04-02 16:38 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +**In its early days, MyGet was lovingly introduced as  “NuGet-as-a-service”. That was the need it was built to solve—an easy way for you to get the benefits of a private NuGet server without the head
still need to delete the two `**` at the start of "In its early days" too!

2020-04-02 17:41 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +[What programming language is most widely used?](/images/2020/What-programming-language-used.jpg "What-programming-language-used")
this one is missing the `!` in front of the `[What programming language]`

2020-04-02 17:48 UTC, m00nlitcat commented
@matthcap it all works now, thanks for the help :)

2020-04-02 18:20 UTC, m00nlitcat commented
@matthcap updated more!

2020-04-02 18:44 UTC, matthcap commented on _posts/2020-03-31-a-product-survey-story.markdown
> +# A Product Survey Story: What We learned 🧐
@m00nlitcat we should capitalize the "l" too!

2020-04-02 21:32 UTC, m00nlitcat commented
@matthcap I've updated the blog :)

2020-04-02 22:14 UTC, matthcap approved these changes
updates look great @m00nlitcat

2020-04-06 21:43 UTC, kacper-r approved these changes
looks good to me

2020-04-07 08:17 UTC, merged